[sdl]
fullscreen = false
window_position = 0,0
output = texture

[cpu]
core = normal
cpu_cycles = 25000

[autoexec]
@echo off
mount C /usr/share/games
mount D /tmp/Catacomb
C:
PATH=C:\DOS;C:\TP5.5;C:\TASM\BIN;C:\BORLANDC\BIN
echo PATH=%PATH%
D:
dir MAKECAT.BAT
MAKECAT.BAT
echo BUILD_DONE
