// Generated by Spice86. Run with: dotnet run -- -e /path/to/PROGRAM.EXE
using System.Collections.Generic;
using System.Linq;

const string OverrideSupplier = "Spice86.Generated.CfgGeneratedOverrideSupplier, Spice86.Generated";
const string ExpectedChecksum = "0B2E33559B9B1AA3005C51B0695AE08B40C60F601C645C50E80C8E4304894BD4";

List<string> spice86Args = [.. args];

if (!spice86Args.Contains("-o") && !spice86Args.Contains("--OverrideSupplierClassName")) {
    spice86Args.Add("--OverrideSupplierClassName");
    spice86Args.Add(OverrideSupplier);
}
if (!spice86Args.Contains("-u") && !spice86Args.Contains("--UseCodeOverride")) {
    spice86Args.Add("--UseCodeOverride");
    spice86Args.Add("true");
}
if (!spice86Args.Contains("-x") && !spice86Args.Contains("--ExpectedChecksum")) {
    spice86Args.Add("--ExpectedChecksum");
    spice86Args.Add(ExpectedChecksum);
}

Spice86.Program.Main([.. spice86Args]);
